### PR TITLE
Enhancements in record plugin

### PR DESCRIPTION
**Pull request by lextiz**
Migrated https://github.com/ccampbell/mousetrap/pull/301.

### CODE REVIEW

**Comment by robincafolla** [comment]
@lextiz It may be the weekend before I get to properly review this (run it locally with the tests). Can you add docs to the readme for the functions? Bonus points for a live example in a [jsfiddle](https://jsfiddle.net/).

**Comment by lextiz** [comment]
Will add the docs.

**Comment by lextiz** [comment]
Actually the original commit has very clear readme addition.

**Comment by robincafolla** [comment]
@lextiz apologies, firstly because I didn't spot the separate plugin readme, and secondly for not having found time to merge this yet. I'm moving house at the moment, and when I've had a chance to code I've been trying to improve the unit-tests ahead of any merges. I promise to try make time tomorrow or on Wednesday to get the changes included.

**Pull request merged**
